### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by saurabh-nikam** [saurabh-nikam/wheel#7]

**Comment by saurabh-nikam** [comment]
Fixes #7
Application is deployed on Heroku
URL(link): https://neetoui-app-saurabh-nikam.herokuapp.com/
username: oliver@example.com
password: welcome

@yedhink Please review it.

**Comment by yedhink** [comment]
@saurabh-nikam You have asked for my review in this issue. But before even I get to review you have closed this issue. It doesn't make sense to me. 

PS: This is an issue. NOT a PR.

I am reopening this issue.

**Comment by yedhink** [comment]
@saurabh-nikam 

- [ ] This validation message doesn't make sense to me. Can you please find a better validation message?
<img width="477" alt="image" src="https://user-images.githubusercontent.com/31244999/191203237-fd32aa66-8bae-496a-82a1-8c3c57bec13d.png">

- [ ] The error message is a sentence. A sentence's first word should be Sentence Case. Also the error message should be something like `Email must be of valid format`
<img width="451" alt="image" src="https://user-images.githubusercontent.com/31244999/191203991-a706078f-7b47-464b-9bd6-471418a0d49d.png">

Once you make these fixes, go ahead and mark this task as completed and continue with the next task.

**Comment by saurabh-nikam** [comment]
Ok, sure yedhin. Thanks 😊

**Comment by saurabh-nikam** [comment]
Changes are done ✅ 
Url : https://neetoui-app-saurabh-nikam.herokuapp.com/
username : oliver@example.com
Password : welcome

**Comment by yedhink** [comment]
GO ahead and mark this task as completed and continue with the next task.
